### ISSUE TITLE
Question on MARS evaluation

### ISSUE THREAD

**Issue by abhishekaich27** [guxinqian/TKP#6]
Thank you for making your code available. The approach is quite simple but effective. I have the following question on MARS evaluation protocol.

Why do you add the query images to gallery? Won't this cause the model to retrieve all the queries from the gallery and give almost ~100% (R1)? What am I missing here? https://github.com/guxinqian/TKP/blob/master/train.py#L407-L411

Reference to your other repo with similar question: https://github.com/guxinqian/AP3D/issues/2#issuecomment-664732310

**Comment by guxinqian** [comment]
In the 47th line of eval_metrics.py, all gallery samples that have the same PID and CamID with query sample are removed. So the test accuracy will not be close to 100%. Adding query set to gallery set is the official evaluation strategy in https://github.com/liangzheng06/MARS-evaluation, otherwise 140 query samples will not have ground truth.
